services:
  backend:
    build: ./backend
    container_name: pipelineops-backend
    ports:
      - "8000:8000"

  ui:
    build: ./ui
    container_name: pipelineops-ui
    ports:
      - "8501:8501"
    depends_on:
      - backend
